### List all messages
GET http://localhost:3000/messages

### Create a new message

POST http://localhost:3000/messages
Content-type: application/json

{
    "content": "Wowza."
}


### Get a message by its ID
GET http://localhost:3000/messages/154